config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_aboard', to: 'pages#all_aboard'
  get 'applications', to: 'all_aboard#applications'
  resources :users do
    resource :profile
  end
  resources :trips do
    resources :trip_applications do
      get 'accept', to: 'trip_applications#accept'
      get 'deny', to: 'trip_applications#deny'
    end
  end
  resources :boats, :passengers, :logs, :stories
end

app/models/trip_application.rb
class TripApplication < ActiveRecord::Base
    
end

app/controllers/trip_applications_controller.rb
class TripApplicationsController < ApplicationController
   before_action :set_application, only: [:show, :destroy, :accept, :deny]
   before_action :only_owner, only: [:accept, :deny]
   before_action :only_owner_or_poster, only: [:show]
   
   def new
       @application = TripApplication.new
   end
   
   def create
      @application = TripApplication.new( application_params )
      @application.trip_id = params[:trip_id]
      @application.owner_id = Trip.find(@application.trip_id).user_id
      @application.user_id = current_user.id
      if @application.save
          flash[:success] = "Application submitted"
          redirect_to trips_path
      else
          flash[:error] = "Application failed"
          render action: :new
      end
   end
   
   def show
      @owner = User.find(Trip.find(@application.trip_id).user_id).profile
   end
   
   def destroy
      @application.destroy
      redirect_to applications_path
   end
   
   def index
      @applications = TripApplication.where("owner_id = ?", current_user.id)
   end
   
   def accept
      if !(@application.accepted || @application.declined)
         @application.accepted = true
         if @application.save
             flash[:success] = "Application accepted"
         else
             flash[:error] = "Accept failed"
         end
         redirect_to applications_path
      end
   end 
   
   def deny
      if !(@application.accepted || @application.declined)
         @application.declined = true
         if @application.save
             flash[:success] = "Application denied"
         else
             flash[:error] = "Deny failed"
         end
         redirect_to applications_path
      end
   end 
   
   private
         def set_application
            if params[:id]
               @application = TripApplication.find(params[:id]) 
            else
               @application = TripApplication.find(params[:trip_application_id])
            end
         end
         
         def only_owner
            redirect_to applications_path unless @application.owner_id == current_user.id
         end
         
         def only_owner_or_poster
            redirect_to applications_path unless (@application.owner_id == current_user.id || @application.user_id == current_user.id)
         end
         
         def application_params
           params.require(:trip_application).permit(:seat_total, :max_price_per_seat, :details, :user_id, :trip_id) 
         end
end

app/views/trip_applications/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <% @applications.each do |application| %>
                <%= link_to trip_trip_application_path(id: application.id, trip_id: application.trip_id) do %>
                    <div class="well row">
                        <div class="col-sm-2">
                            <h3><i class="fa fa-user-times"></i> <%= application.seat_total.to_s %></h3>
                        </div>
                        <div class="col-sm-2">
                            <h3><i class="fa fa-dollar"></i> <%= application.max_price_per_seat.to_s %> <small>each</small></h3>
                        </div>
                        <div class="col-sm-8">
                            <p><%= application.details %></p>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/trip_applications/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
                <h2 class="text-center">New Application</h2>
                <%= form_for @application, url: trip_trip_applications_path do |f| %>
                    <div class="field form-group">
                        <%= f.label :seat_total %>
                        <%= f.number_field :seat_total, class: "form-control" %>
                    </div>
                    <div class="field form-group">
                        <%= f.label :max_price_per_seat %>
                        <%= f.number_field :max_price_per_seat, class: "form-control" %>
                    </div>
                    <div class="field form-group">
                        <%= f.label :details %>
                        <%= f.text_area :details, class: "form-control" %>
                    </div>
                    <div class="field form-group">
                        <%= f.submit :Submit, class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/trip_applications/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well row">
                <div class="col-sm-2">
                    <h3><i class="fa fa-user-times"></i> <%= @application.seat_total.to_s %></h3>
                </div>
                <div class="col-sm-2">
                    <h3><i class="fa fa-dollar"></i> <%= @application.max_price_per_seat.to_s %> <small>each</small></h3>
                </div>
                <div class="col-sm-8">
                    <p><%= @application.details %></p>
                </div>
            </div>
            <% if @application.accepted %>
                <div class="bg-success">
                    <h3><i class="fa fa-check"></i> Accepted!</h3>
                </div>
            <% end %>
            <% if @application.declined %>
                <div class="bg-danger">
                    <h3><i class="fa fa-ban"></i> Declined</h3>
                </div>
            <% end %>
            
            <% if @owner.user_id == current_user.id && !@application.accepted && !@application.declined %>
                <%= link_to "Accept", trip_trip_application_accept_path(trip_id: @application.trip_id, trip_application_id: @application.id), class: "btn btn-success" %>
                <%= link_to "Deny", trip_trip_application_deny_path(trip_id: @application.trip_id, trip_application_id: @application.id), class: "btn btn-danger pull-right" %>
            <% end %>
        </div>
    </div>
</div>