config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_aboard', to: 'pages#all_aboard'
  get 'applications', to: 'all_aboard#applications'
  resources :users do
    resource :profile
  end
  resources :trips do
    resources :trip_applications do
      get 'accept', to: 'trip_applications#accept'
      get 'deny', to: 'trip_applications#deny'
    end
  end
  resources :boats, :passengers, :logs, :stories
end

app/views/pages/_aamenu.html.erb
<div class="row aamenu">
    
    <div class="col-md-2">
        <%= link_to "Trips", trips_path, class: "btn btn-lg btn-block" %>
    </div>
    <div class="col-md-2">
        <%= link_to "Applications", applications_path, class: "btn btn-lg btn-block" %>
    </div>
    <div class="col-md-4">
        <%= link_to all_aboard_path do %>
            <h1 class="text-center">All Aboard</h1>
        <% end %>
    </div>
    <div class="col-md-2 col-md-offset-2">
        <%= link_to "Looking for Rides", passengers_path, class: "btn btn-lg btn-block" %>
    </div>
</div>

app/views/pages/about.html.erb
<div class="container">
    <div class='row'>
        <div class='col-md-6 col-md-offset-3 text-center'>
            <h2>Merasheen About</h2>
        </div>
    </div>
</div>

app/views/pages/all_aboard.html.erb
<div class="container">
    <%= render "aamenu" %>
    <div class="row">
        <div class="col-md-4 aaimage">
            <%= image_tag "http://i.imgur.com/kuD8flzl.jpg" %>
        </div>
        <div class="aamenu-jumbo text-center">
            <h3>Find a ride to the island</h3>
            <h3>Or help others get to the island</h3>
            <h4>You can even earn money for your effort if you choose</h4>
            <p>All aboard is a system to link together boat operators with people 
            looking to get to Merasheen Island. The operators may charge money if
            they like however you will have to make you own payment arrangements</p>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<div class='home-callout text-center container-fluid'>
    <h2>Merasheen Home Page</h2>
    <h4>Welcome home</h4>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="well">
            <%= link_to all_aboard_path do %>
                <h1 class="text-center">All Aboard</h1>
            <% end %>
            <h3>Find a ride to the island</h3>
            <h3>Or help others get to the island</h3>
            <h4>You can even earn money for your effort if you choose</h4>
            <p>All aboard is a system to link together boat operators with people 
            looking to get to Merasheen Island. The operators may charge money if
            they like however you will have to make you own payment arrangements</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="well">
            <%= link_to logs_path do %>
                <h1 class="text-center">Log Book</h1>
            <% end %>
            <h3>Tell us about your trip to the island</h3>
            <p>Leave a log of your trip and see logs left by others. Keep up to date 
            on what is happening on the island</p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="well">
            <%= link_to stories_path do %>
                <h1 class="text-center">Stories</h1>
            <% end %>
            <h3>Read stories from others on the island</h3>
            <h3>Tell us your stories from the island</h3>
            <p>Stories from the island</p>
            </div>
        </div>
    </div>
</div>
<!--<% if user_signed_in? %>-->
<!--    <% if current_user.profile %>-->
<!--        <%= link_to "Update profile", edit_user_profile_path(user_id: current_user.id) %>-->
<!--    <% else %>-->
<!--        <%= link_to "Create profile", new_user_profile_path(user_id: current_user.id) %>-->
<!--    <% end %>-->
<!--<% end %>-->