config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_aboard', to: 'pages#all_aboard'
  get 'applications', to: 'all_aboard#applications'
  resources :users do
    resource :profile
  end
  resources :trips do
    resources :trip_applications do
      get 'accept', to: 'trip_applications#accept'
      get 'deny', to: 'trip_applications#deny'
    end
  end
  resources :boats, :passengers, :logs, :stories
end

app/models/boat.rb
class Boat < ActiveRecord::Base
    has_attached_file :avatar,
                        :styles => { :medium => "300x300>", :thumb => "100x100>" },
                        :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
    # GET /boats/new
    def new
        @boat = Boat.new
    end
    
    # GET /boats/:id
    def show
       @boat = Boat.find(params[:id]) 
    end
    
    # POST /boats
    def create
        @boat = Boat.new( boat_params )
        if @boat.save
            flash[:success] = "Boat created"
            redirect_to boat_path(id: @boat.id)
        else
            flash[:error] = "Creation failed"
            render action: :new
        end
    end
    
    # GET /boats/:id/edit
    def edit
       @boat = Boat.find(params[:id]) 
    end
    
    # PUT /boats/:id
    def update
        @boat = Boat.find(params[:id])
        if @boat.update_attributes( boat_params )
           flash[:success] = "Boat Updated"
           redirect_to boat_path(id: params[:id])
        else
            flash[:error] = "Update failed"
            render :edit
        end
    end
    
    # GET /boats
    def index
       @boats = Boat.all 
    end
    
    private
        def boat_params
           params.require(:boat).permit(:name, :owner, :home_port, :capacity, :price, :speed, :avatar, :comments) 
        end
end

app/views/boats/_form.html.erb
<%= form_for @boat, :html => { :multipart => true } do |f| %>
    <div class='field form-group'>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :owner %>
        <%= f.text_field :owner, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :home_port %>
        <%= f.text_field :home_port, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :capacity %>
        <%= f.text_field :capacity, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :price %>
        <%= f.text_field :price, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :speed %>
        <%= f.text_field :speed, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.label :comments %>
        <%= f.text_area :comments, class: 'form-control' %>
    </div>
    <div class='field form-group'>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/boats/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-6 col-md-offset-3'>
            <div class='well'>
                <h1>Edit Boat</h1>
                <%= render "form" %>
            </div>
        </div>
    </div>
</div>

app/views/boats/index.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-8 col-md-offset-2'>
            <% @boats.each do |boat| %>
                <div class='well row'>
                    <div class='col-sm-4'>
                        <%= link_to boat_path(id: boat.id) do %>
                            <h2><%= boat.name %></h2>
                        <% end %>
                    </div>
                    <div class='col-sm-4'>
                        <h4><%= "Owned by: " << boat.owner %></h4>
                        <h4><%= "Out of: " << boat.home_port %></h4>
                    </div>
                    <div class='col-sm-4'>
                        <h4><%= "$" << boat.price.to_s << "0+" %></h4>
                        <h6><%= "Top speed: " << boat.speed.to_s << " knots" %></h6>
                        <h6><%= "Capacity: " << boat.capacity.to_s %></h6>
                    </div>
                </div>
            <% end %>
        </div>
        <div class='col-md-1'>
            <%= link_to "New Boat", new_boat_path, class: 'btn btn-primary' %>
        </div>
    </div>
</div>

app/views/boats/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-6 col-md-offset-3'>
            <div class='well'>
                <h1>New Boat</h1>
                <%= form_for @boat, :html => { :multipart => true } do |f| %>
                    <div class='field form-group'>
                        <%= f.label :name %>
                        <%= f.text_field :name, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :owner %>
                        <%= f.text_field :owner, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :home_port %>
                        <%= f.text_field :home_port, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :capacity %>
                        <%= f.text_field :capacity, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :price %>
                        <%= f.text_field :price, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :speed %>
                        <%= f.text_field :speed, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :avatar %>
                        <%= f.file_field :avatar, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.label :comments %>
                        <%= f.text_area :comments, class: 'form-control' %>
                    </div>
                    <div class='field form-group'>
                        <%= f.submit 'Submit', class: 'btn btn-primary' %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/boats/show.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-md-8 col-md-offset-2'>
            <div class='well'>
                <h1><%= @boat.name %></h1>
                <%= image_tag @boat.avatar.url %>
                <h4><%= "Owned by: " << @boat.owner %></h4>
                <h4><%= "Out of: " << @boat.home_port %></h4>
                <h4><%= "$" << @boat.price.to_s << "0+" %></h4>
                <h6><%= "Top speed: " << @boat.speed.to_s << " knots" %></h6>
                <h6><%= "Capacity: " << @boat.capacity.to_s %></h6>
            </div>
            <%= link_to "Edit boat", edit_boat_path(id: params[:id]), class: 'btn btn-primary' %>
            <%= link_to "New trip", new_trip_path, class: 'btn btn-default' %>
        </div>
    </div>
</div>