config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'all_aboard', to: 'pages#all_aboard'
  get 'applications', to: 'all_aboard#applications'
  resources :users do
    resource :profile
  end
  resources :trips do
    resources :trip_applications do
      get 'accept', to: 'trip_applications#accept'
      get 'deny', to: 'trip_applications#deny'
    end
  end
  resources :boats, :passengers, :logs, :stories
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Merasheen</title>
    <%= csrf_meta_tags %>
    
    <link href="//fonts.googleapis.com/css?family=Oswald:400,700" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_path, class: "navbar-brand" do %>
            <i class='fa fa-ship'></i>
             Merasheen
          <% end %>
        </div>
        
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <!--TempLink-->
            <li><%= link_to "All Aboard", all_aboard_path %></li>
            <li><%= link_to "Log Book", logs_path %></li>
            <li><%= link_to "Stories", stories_path %></li>
            <!--<li><%= link_to "Boats", boats_path %></li>-->
            <li><%= link_to "About", about_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Community", users_path %></li>
              <% if current_user.profile %>
                  <li><%= link_to current_user.profile.first_name << " " << current_user.profile.last_name[0] << ".", user_path(id: current_user.id) %></li>
              <% else %>
                  <li><%= link_to "Create profile", new_user_profile_path(user_id: current_user.id) %></li>
              <% end %>
            <% end %>
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn" %>
            <% else %>
              <%= link_to "Login", new_user_session_path, class: "btn btn-default navbar-btn" %>
              <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default navbar-btn" %>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>